service: serverless-snipetts-vpc

provider:
  name: aws

resources:
  Resources:
    vpc:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsHostnames: false
        EnableDnsSupport: false
        InstanceTenancy: default
    subnetA:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone:
          Fn::Select:
            - 0
            - Fn::GetAZs: ""
        CidrBlock: 10.0.0.0/18
        MapPublicIpOnLaunch: false
        VpcId: !Ref vpc
    subnetB:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone:
          Fn::Select:
            - 1
            - Fn::GetAZs: ""
        CidrBlock: 10.0.64.0/18
        MapPublicIpOnLaunch: false
        VpcId: !Ref vpc
    subnetPrivateA:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone:
          Fn::Select:
            - 0
            - Fn::GetAZs: ""
        CidrBlock: 10.0.128.0/18
        MapPublicIpOnLaunch: false
        VpcId: !Ref vpc
    subnetPrivateB:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone:
          Fn::Select:
            - 1
            - Fn::GetAZs: ""
        CidrBlock: 10.0.192.0/18
        MapPublicIpOnLaunch: false
        VpcId: !Ref vpc
  Outputs:
    vpc:
      Value: !Ref vpc
    subnetA:
      Value: !Ref subnetA
    subnetB:
      Value: !Ref subnetB
    subnetPrivateA:
      Value: !Ref subnetPrivateA
    subnetPrivateB:
      Value: !Ref subnetPrivateB
